opcache.enable=1
opcache.memory_consumption=256
opcache.interned_strings_buffer=16
opcache.max_accelerated_files=20000
; Safe default when bind-mounting source in docker-compose (dev)
opcache.validate_timestamps=1
opcache.revalidate_freq=2
